export const PRODUCTS_API_CALL_REQUEST = "PRODUCTS_API_CALL_REQUEST";
export const PRODUCTS_API_CALL_SUCCESS = "PRODUCTS_API_CALL_SUCCESS";
export const PRODUCTS_API_CALL_FAILURE = "PRODUCTS_API_CALL_FAILURE";