export const PRODUCTS_API_CALL_REQUEST = "PRODUCTS_API_CALL_REQUEST";
export const PRODUCTS_API_CALL_SUCCESS = "PRODUCTS_API_CALL_SUCCESS";
export const PRODUCTS_API_CALL_FAILURE = "PRODUCTS_API_CALL_FAILURE";

export const PRODUCT_DETAILS_API_CALL_REQUEST = "PRODUCT_DETAILS_API_CALL_REQUEST";
export const PRODUCT_DETAILS_API_CALL_SUCCESS = "PRODUCT_DETAILS_API_CALL_SUCCESS";
export const PRODUCT_DETAILS_API_CALL_FAILURE = "PRODUCT_DETAILS_API_CALL_FAILURE";